In [8]:
!pip install -Uq pymcel

In [21]:
import pymcel as pc
import numpy as np

In [10]:
m_tierra = pc.constantes.M_earth
m_sol = pc.constantes.M_sun

Posiciones de la Tierra y el Sol:

In [11]:
tabla, jd, X = pc.consulta_horizons(id ='399', location = '@SSB', epochs = '2026-2-19') #baricentro del sistema solas SSB, 339 codigo de la Tierra
r_tierra = X[0 : 3]

In [18]:
tabla, jd, X = pc.consulta_horizons(id = '0', location = '@SSB', epochs = '2026-2-19')
r_sol = X[0 : 3]

Calculamos el vector entre ellos:

In [19]:
r_tierra_sol = r_tierra - r_sol

La fuerza entre ellos:

In [22]:
F_tierra_sol = pc.constantes.G * m_tierra * m_sol * r_tierra_sol / np.linalg.norm(r_tierra_sol)**3
F_tierra_sol

array([-3.15179429e+22,  1.79516139e+22,  3.65410599e+18])

Calculemos la fuerza que ejerce el Sol sobre la Luna:

In [23]:
m_luna = pc.constantes.mu_moon / pc.constantes.G

tabla, jd_moon, X_moon = pc.consulta_horizons(id='301', location='@SSB', epochs='2026-2-19')
r_luna = X_moon[0:3]

r_luna_sol = r_luna - r_sol

F_luna_sol = pc.constantes.G * m_luna * m_sol * r_luna_sol / np.linalg.norm(r_luna_sol)**3
F_luna_sol

array([-3.89390496e+20,  2.22197278e+20,  6.35769036e+16])

Calculemos la fuerza que ejerce la Tierra sobre la Luna:

In [24]:
r_luna_tierra = r_luna - r_tierra

F_luna_tierra = pc.constantes.G * m_luna * m_tierra * r_luna_tierra / np.linalg.norm(r_luna_tierra)**3
F_luna_tierra

array([ 1.99557718e+20, -4.07017512e+19,  3.23394560e+18])

Calculamos la magnitud de ambas fuerzas:

In [25]:

magnitud_F_luna_sol = np.linalg.norm(F_luna_sol)
magnitud_F_luna_tierra = np.linalg.norm(F_luna_tierra)

print(f"Magnitud de la fuerza del Sol sobre la Luna: {magnitud_F_luna_sol:.3e} N")
print(f"Magnitud de la fuerza de la Tierra sobre la Luna: {magnitud_F_luna_tierra:.3e} N")

# Comparación
if magnitud_F_luna_sol > magnitud_F_luna_tierra:
    print(f"La fuerza del Sol sobre la Luna es {magnitud_F_luna_sol / magnitud_F_luna_tierra:.2f} veces mayor que la fuerza de la Tierra sobre la Luna.")
elif magnitud_F_luna_tierra > magnitud_F_luna_sol:
    print(f"La fuerza de la Tierra sobre la Luna es {magnitud_F_luna_tierra / magnitud_F_luna_sol:.2f} veces mayor que la fuerza del Sol sobre la Luna.")
else:
    print("Ambas fuerzas tienen magnitudes similares.")

Magnitud de la fuerza del Sol sobre la Luna: 4.483e+20 N
Magnitud de la fuerza de la Tierra sobre la Luna: 2.037e+20 N
La fuerza del Sol sobre la Luna es 2.20 veces mayor que la fuerza de la Tierra sobre la Luna.


# Task
Obtener la posición del Sol respecto al baricentro del sistema solar (SSB) para la fecha '2026-2-19', calcular el vector posición Tierra-Sol, la distancia Tierra-Sol, y finalmente la fuerza gravitacional entre la Tierra y el Sol, presentando la posición del Sol y el valor de la fuerza calculada.

## Obtener Posición del Sol

### Subtask:
Consultar la posición del Sol respecto al baricentro del sistema solar (SSB) utilizando `pymcel.consulta_horizons` para la fecha '2026-2-19'.


**Reasoning**:
To get the position of the Sun relative to the Solar System Barycenter (SSB), I will use the `pc.consulta_horizons` function with the specified parameters, then extract the position vector.



In [12]:
tabla_sol, jd_sol, X_sol = pc.consulta_horizons(id='10', location='@SSB', epochs='2026-2-19')
r_ssb_sol = X_sol[0 : 3]
print(f"Posición del Sol (r_ssb_sol): {r_ssb_sol}")

Posición del Sol (r_ssb_sol): [-4.06662772e+08 -8.24801720e+08  1.86896594e+07]


**Reasoning**:
Now that we have the position of the Sun relative to the SSB (`r_ssb_sol`) and the Earth relative to the SSB (`r_sol_tierra`, though it's actually `r_ssb_earth` but named `r_sol_tierra` in the notebook), we can calculate the vector position of the Earth relative to the Sun, which is `r_sol_tierra - r_ssb_sol`.



In [13]:
# r_tierra_sol = r_ssb_sol - r_sol_tierra
# print(f"Vector posición Tierra-Sol (r_tierra_sol): {r_tierra_sol}")

**Reasoning**:
To determine the distance between the Earth and the Sun, I will calculate the Euclidean norm (magnitude) of the `r_tierra_sol` vector, which represents the vector position of the Sun relative to the Earth.



In [14]:
# import numpy as np
# distancia_tierra_sol = np.linalg.norm(r_tierra_sol)
# print(f"Distancia Tierra-Sol: {distancia_tierra_sol} km")

**Reasoning**:
To calculate the gravitational force, I will use Newton's Law of Universal Gravitation (F = G * (m1 * m2) / r^2). First, I need to obtain the gravitational constant G from `pymcel.constantes` and then apply the formula using the masses of the Earth and the Sun, and the calculated distance between them.



In [15]:
# G = pc.constantes.G
# fuerza_gravitacional = G * (m_tierra * m_sol) / (distancia_tierra_sol * 1000)**2 # Convert km to meters for the formula
# print(f"Fuerza gravitacional entre la Tierra y el Sol: {fuerza_gravitacional} Newtons")

## Final Task

### Subtask:
Presentar la posición del Sol y el valor de la fuerza gravitacional calculada.


## Summary:

### Q&A
*   **What is the position of the Sun relative to the Solar System Barycenter (SSB) for '2026-2-19'?**
    The Sun's position relative to the SSB is \[-4.06662772e+08 -8.24801720e+08 1.86896594e+07].
*   **What is the calculated gravitational force between the Earth and the Sun?**
    The gravitational force between the Earth and the Sun is 3.6243471427072424e+16 Newtons.

### Data Analysis Key Findings
*   The position of the Sun relative to the Solar System Barycenter (SSB) on '2026-2-19' was found to be \[-4.06662772e+08 -8.24801720e+08 1.86896594e+07].
*   The vector position of the Sun relative to the Earth was calculated as \[ 1.28041114e+11 -7.39845539e+10 3.79776776e+06].
*   The distance between the Earth and the Sun was determined to be 147879143406.5007 km.
*   The gravitational force between the Earth and the Sun was calculated to be 3.6243471427072424e+16 Newtons.

### Insights or Next Steps
*   This calculation provides a foundational understanding of the gravitational interaction at a specific point in time. It could be expanded to analyze the variation of this force over longer periods due to orbital changes.
*   The results can be used as input for simulations of orbital mechanics or for calculating other related physical phenomena.
